name: CI/CD for Dev

on:
  push:
    branches:
      - dev

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies (Frontend)
        working-directory: ./frontend
        run: npm install

      - name: Run Unit Tests (Frontend)
        working-directory: ./frontend
        run: npm test

      - name: Install Dependencies (Backend)
        working-directory: ./backend
        run: npm install

      - name: Run Unit Tests (Backend)
        working-directory: ./backend
        run: npm test

      - name: Merge Dev to Main
        if: success()
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: dev
          target_branch: main
          message: Merge my-feature into dev
          github_token: ${{ secrets.GITHUB_TOKEN }}
