name: CI/CD for Main

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies (Frontend)
        working-directory: ./frontend
        run: npm install

      - name: Run Unit Tests (Frontend)
        working-directory: ./frontend
        run: npm test

      - name: Install Dependencies (Backend)
        working-directory: ./backend
        run: npm install

      - name: Run Unit Tests (Backend)
        working-directory: ./backend
        run: npm test

      - name: Run E2E Tests
        run: |
          npm install selenium-webdriver
          npm run test:e2e

      - name: Build Docker Images
        run: docker-compose build

      - name: Push Docker Images to DockerHub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker-compose push
